project:
    type: website
website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Playground"
        href: playground.qmd
format:
  html:
    page-layout: article
    css: style.css
execute:
  freeze: auto
