project:
  type: website
  preview: 
    port: 1111
    browser: false
website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
format:
  html:
    page-layout: article
    css: style.css
execute:
  freeze: auto
